import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { AttemptState, DeterministicRunner, FakeHarnessAdapter, RunnerError, atomicWrite, runWithHardTimeout } from "../src/runner.js";
import { treeDigest } from "../src/digests.js";

const root = new URL("..", import.meta.url).pathname;
async function fixture(scenario: ConstructorParameters<typeof FakeHarnessAdapter>[0] = "success") {
  const dir = await mkdtemp(join(tmpdir(), "aht-runner-")), state = join(dir, "state"); await mkdir(state); await writeFile(join(state, "input.txt"), "input\n"); const request = JSON.parse(await readFile(join(root, "spec/examples/run-request.example.json"), "utf8")); request.run_id = `run-${scenario}`; request.campaign_id = "fake-campaign"; request.experiment.id = "fake-experiment"; request.workspace.initial_tree_digest = await treeDigest(state); request.task.initial_tree_digest = request.workspace.initial_tree_digest; request.workspace.path = "workspace"; request.configuration.harness = { family: "fake", interface: "test", adapter_id: "fake-adapter", adapter_version: "0.2.0", runtime_version: "0.2.0", config: {} }; request.invocation.argv = ["fake"]; request.invocation.working_directory = "workspace"; const evaluator = { evaluate: async () => ({ schema_version: "0.2.0", task_id: request.task.id, task_version: request.task.version, status: "ok", started_at: "2026-01-01T00:00:00Z", finished_at: "2026-01-01T00:00:00Z", duration_ms: 0, checks: [{ id: "core", score: 1, passed: true }] }) }; return { dir, state, request, evaluator, adapter: new FakeHarnessAdapter(scenario) };
}
test("M0 state and immutable artifacts fail closed", async () => { const s = new AttemptState(); assert.throws(() => s.transition("running"), RunnerError); s.transition("request-finalized"); s.transition("materialized"); s.transition("running"); s.transition("captured"); s.finalize(); assert.throws(() => s.finalize(), /cannot transition/); const d = await mkdtemp(join(tmpdir(), "atomic-")); try { await atomicWrite(join(d, "a"), "one"); await assert.rejects(atomicWrite(join(d, "a"), "two")); } finally { await rm(d, { recursive: true, force: true }); } });
test("M0 finalization is legal only from captured/evaluated and atomic publication never replaces", async () => { const s = new AttemptState(); assert.throws(() => s.finalize(), /cannot transition/); s.transition("request-finalized"); s.transition("materialized"); s.transition("running"); s.transition("captured"); s.finalize(); const d = await mkdtemp(join(tmpdir(), "atomic-race-")); try { await Promise.allSettled([atomicWrite(join(d, "x"), "one"), atomicWrite(join(d, "x"), "two")]); assert.equal(await readFile(join(d, "x"), "utf8") === "one" || await readFile(join(d, "x"), "utf8") === "two", true); } finally { await rm(d, { recursive: true, force: true }); } });
test("hard timeout wins when an adapter ignores cooperative abort and invokes process termination", async () => { let terminated = false; const adapter = { run: async () => await new Promise<any>(() => undefined), terminate: async () => { terminated = true; } }; const result = await runWithHardTimeout(adapter, { workspace: ".", prompt: "", request: {}, signal: new AbortController().signal }, 0); assert.equal(result.terminal, "wall_time_exhausted"); assert.equal(terminated, true); });
test("M1-M3 request, fake capture, evaluation and immutable result", async () => { const f = await fixture(); try { const result = await new DeterministicRunner().run(f.request, { root: f.dir, stateSource: f.state, prompt: "p", adapter: f.adapter, evaluator: f.evaluator, taskChecks: [{ id: "core", weight: 1, required: true }], schemaDirectory: join(root, "spec/schemas") }); assert.equal(result.terminal.reason, "agent_completed"); assert.equal(result.evaluation.artifact_quality_score, 1); assert.equal(JSON.parse(await readFile(join(f.dir, "results/fake-experiment/fake-campaign/runs/run-success/run.json"), "utf8")).artifacts.length, 8); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("M2 timeout preserves partial work and still evaluates it", async () => { const f = await fixture("timeout"); try { const result = await new DeterministicRunner().run(f.request, { root: f.dir, stateSource: f.state, prompt: "p", adapter: f.adapter, evaluator: f.evaluator, taskChecks: [{ id: "core", weight: 1, required: true }] }); assert.equal(result.terminal.reason, "wall_time_exhausted"); assert.equal(result.evaluation.status, "ok"); assert.equal(result.metrics.tokens.status, "unavailable"); assert.ok(await readFile(join(f.dir, "results/fake-experiment/fake-campaign/runs/run-timeout/workspace/fake-harness.txt"))); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("M1 digest mismatch prevents harness launch with environment attribution", async () => { const f = await fixture(); f.request.workspace.initial_tree_digest = `tree-sha256-v1:${"f".repeat(64)}`; try { const result = await new DeterministicRunner().run(f.request, { root: f.dir, stateSource: f.state, prompt: "p", adapter: f.adapter, evaluator: f.evaluator, taskChecks: [{ id: "core", weight: 1, required: true }] }); assert.equal(result.terminal.reason, "environment_error"); assert.equal(result.errors[0].attribution, "environment"); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("M3 errors never fabricate a score and persisted secret sentinels are redacted", async () => { const f = await fixture("provider-error"); f.request.invocation.secret_names = ["TOP_SECRET"]; const adapter = { run: async (input: Parameters<FakeHarnessAdapter["run"]>[0]) => ({ ...(await f.adapter.run(input)), stderr: "TOP_SECRET" }) }; try { const result = await new DeterministicRunner().run(f.request, { root: f.dir, stateSource: f.state, prompt: "p", adapter, evaluator: { evaluate: async () => { throw new Error("broken evaluator"); } }, taskChecks: [{ id: "core", weight: 1, required: true }] }); assert.equal(result.terminal.attribution, "provider"); assert.equal(result.evaluation.status, "error"); assert.equal(JSON.stringify(result).includes("TOP_SECRET"), false); assert.match(await readFile(join(f.dir, "results/fake-experiment/fake-campaign/runs/run-provider-error/stderr.log"), "utf8"), /\[REDACTED\]/); } finally { await rm(f.dir, { recursive: true, force: true }); } });
